# Generated by Django 5.0.6 on 2024-07-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane_id', models.CharField(max_length=100, unique=True)),
                ('traffic_signal', models.CharField(max_length=10)),
                ('vehicle_count', models.IntegerField(default=0)),
            ],
        ),
    ]
