# Generated by Django 5.0.6 on 2024-07-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_lane'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficsignal',
            name='status',
            field=models.CharField(default='unknown', max_length=10),
        ),
    ]
