# Generated by Django 5.0.6 on 2024-07-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_trafficsignal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficsignal',
            name='status',
        ),
        migrations.AddField(
            model_name='trafficsignal',
            name='timer_duration',
            field=models.IntegerField(default=0),
        ),
    ]
