# Generated by Django 5.0.6 on 2024-07-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0005_accident_remove_trafficsignal_timer_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Accident',
        ),
    ]
