# Generated by Django 5.0.6 on 2024-07-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0006_accidentalert_delete_accident'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.ImageField(upload_to='accidents/')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
