# Generated by Django 5.0.6 on 2024-07-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0007_accident'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accident',
        ),
        migrations.DeleteModel(
            name='Lane',
        ),
        migrations.RemoveField(
            model_name='accidentalert',
            name='message',
        ),
        migrations.AddField(
            model_name='accidentalert',
            name='image',
            field=models.ImageField(default='default_image_path.jpg', upload_to='accidents/'),
        ),
        migrations.AlterField(
            model_name='trafficsignal',
            name='lane_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='trafficsignal',
            name='vehicle_count',
            field=models.IntegerField(),
        ),
    ]
