# Generated by Django 5.0.6 on 2024-07-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0008_delete_accident_delete_lane_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentalert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accidents/'),
        ),
    ]
