# Generated by Django 5.0.6 on 2024-07-29 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0009_alter_accidentalert_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accidentalert',
            old_name='image',
            new_name='frame',
        ),
        migrations.RenameField(
            model_name='accidentalert',
            old_name='timestamp',
            new_name='time',
        ),
    ]
