# Generated by Django 5.0.6 on 2024-07-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0010_rename_image_accidentalert_frame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentalert',
            name='frame',
            field=models.ImageField(blank=True, null=True, upload_to='accidents_frames/'),
        ),
    ]
